version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    build:
        commands:
            - aws --output text s3 sync --delete --sse AES256 --acl private --only-show-errors s3://$S3_SOURCE_BUCKET s3://$S3_BUCKET
    post_build:
        commands:
            - aws --output text cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths /\*
