name: KINOFF staging -> live

on:
    release:
        types: [ published ]
        branches: [ staging_kinoff ]
    workflow_dispatch:

    # schedule:
    #     - cron: '1 0-7 * * *'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        -   name: copy file via ssh key
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USER }}
                key: ${{ secrets.DEPLOY_KEY }}
                source: ${{ secrets.DEPLOY_STAGING_KINOFF_PATH }}
                target: ${{ secrets.DEPLOY_LIVE_KINOFF_PATH }}

        -
            name: Github->Slack notification Webhook action
            uses: craftech-io/slack-action@v1
            with:
                slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()

