# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches: [ DeploymentTest ]
    workflow_dispatch:
        inputs:
            userName:
                description: 'Person who pushed the button'
                required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Tagasiside
      run: echo "${{ github.event.inputs.userName }} vajutas nuppu"

    - name: feedback to slack
    id: feedback
    uses: marianntapfer/post-to-slack@master
    with:
        slackUserId: ${{ github.event.inputs.slackUserId }}
        privateChannel: ${{ github.event.inputs.privateChannel  }}
    if: always()
