name: PÖFF staging -> live

on:
    release:
        types: [ published ]
        branches: [ staging_poff ]
    workflow_dispatch:
    # schedule:
    #     - cron: '1 0-7 * * *'

jobs:
    deploy:
        name: SCP files to server
        runs-on: ubuntu-latest
        steps:
        -   name: set up
            run: mkdir temp

        -   name: scp attempt
            run: echo "${{ secrets.DEPLOY_KEY }}" | scp -i /dev/stdin virt84398@inscaping.eu:domeenid/www.inscaping.eu/web/poff_staging/* temp/

        # -   name: copy files from server
        #     uses: appleboy/scp-action@master
        #     env:
        #         host: inscaping.eu
        #         username: virt84398
        #         key: ${{ secrets.DEPLOY_KEY }}
        #     with:
        #         source: domeenid/www.inscaping.eu/web/poff_staging/*
        #         target: temp/

        # -   name: copy files to server
        #     uses: appleboy/scp-action@master
        #     env:
        #         host: inscaping.eu
        #         username: virt84398
        #         key: ${{ secrets.DEPLOY_KEY }}
        #     with:
        #         source: temp/*
        #         target: domeenid/www.inscaping.eu/web/poff_live/

        # -
        #     name: Github->Slack notification Webhook action
        #     uses: craftech-io/slack-action@v1
        #     with:
        #         slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        #     if: always()



