name: Build and publish LIVE POFF site

# on:
#     release:
#         types: [published]
#         branches:
#             - staging_poff

    # schedule:
    #     - cron: '1 0-7 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: Install node dependencies
          run: npm install

        - name: Build Project
          run: node ./node_modules/entu-ssg/src/build.js ./entu-ssg.yaml full

        - name: Copy Assets
          run: cp -R assets build/assets

        # - name: List output files
        #   run: ls

        - name: rsync deployments
          uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzr --delete
            path: build/
            # remote_path: ${{ secrets.DEPLOY_PATH }}
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}

        - name: Github->Slack notification Webhook action
          uses: craftech-io/slack-action@v1
          with:
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()



