name: PÖFF staging -> live

on:
    release:
        types: [ published ]
        branches: [ staging_poff ]
    workflow_dispatch:
    # schedule:
    #     - cron: '1 0-7 * * *'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        -   name: copy file via ssh key
            uses: appleboy/scp-action@master
            with:
                host: inscaping.eu
                username: virt84398
                key: ${{ secrets.DEPLOY_KEY }}
                source: /data01/virt84398/domeenid/www.inscaping.eu/web/poff_staging
                target: /data01/virt84398/domeenid/www.inscaping.eu/web/poff_live

        -
            name: Github->Slack notification Webhook action
            uses: craftech-io/slack-action@v1
            with:
                slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()



