name: justfilm.ee

on:
    release:
        types: [ published ]
        branches: [ staging_justfilm ]
    workflow_dispatch:
        inputs:
            userName:
                description: 'Person who pushed the button'
                required: true

jobs:
    deploy:
        name: SCP files to server
        runs-on: ubuntu-latest
        steps:
        -   name: ls -a via ssh
            uses: fifsky/ssh-action@master
            with:
                command: scp -r domeenid/www.inscaping.eu/web/just_staging/* justfilm:domeenid/www.justfilm.ee/web2020/just_live/
                host: inscaping.eu
                user: virt84398
                key: ${{ secrets.DEPLOY_KEY }}

        -   name: Github->Slack notification Webhook action
            uses: craftech-io/slack-action@v1
            with:
                slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()

        # - name: feedback to slack
        #   id: feedback
        #   uses: marianntapfer/post-to-slack@master
        #   with:
        #     slackUserId: ${{ github.event.inputs.slackUserId }}
        #     privateChannel: ${{ github.event.inputs.privateChannel  }}
        # if: always()
