name: Build and publish LIVE INDUSTRY site

on:
    release:
        types: [published]
        branches: [staging_industry]

    # schedule:
    #     - cron: '1 0-7 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        - name: rsync deployments
          uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzr
            path: ${{ secrets.DEPLOY_STAGING_INDUSTRY_PATH }}
            remote_path: ${{ secrets.DEPLOY_LIVE_INDUSTRY_PATH }}
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}

        - name: Github->Slack notification Webhook action
          uses: craftech-io/slack-action@v1
          with:
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()



