name: poff.ee stage2live inscaping2poff

on:
    release:
        types: [ published ]
        branches: [ staging_poff ]
    workflow_dispatch:

jobs:
    deploy:
        name: SCP files to server
        runs-on: ubuntu-latest
        steps:
        -   name: executing remote ssh commands using ssh key
            uses: appleboy/ssh-action@master
            with:
                host: inscaping.eu
                username: virt84398
                port: 22
                key: ${{ secrets.DEPLOY_KEY }}
                script: scp -r domeenid/www.inscaping.eu/web/poff_staging poff:domeenid/www.poff.ee/web2020/poff_live

        - name: Github->Slack notification Webhook action
          uses: craftech-io/slack-action@v1
          with:
            slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()
