name: kinoff.inscaping.eu/

on:
    release:
        types: [ published ]
        branches: [ staging_kinoff ]
    workflow_dispatch:

jobs:
    deploy:
        name: SCP files to server
        runs-on: ubuntu-latest
        steps:
        -   name: ls -a via ssh
            uses: fifsky/ssh-action@master
            with:
                command: scp -r domeenid/www.inscaping.eu/web/kinoff_staging/* poff:domeenid/www.poff.ee/web2020/kinoff_live/
                host: inscaping.eu
                user: virt84398
                key: ${{ secrets.DEPLOY_KEY }}

        -
            name: Github->Slack notification Webhook action
            uses: craftech-io/slack-action@v1
            with:
                slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()
