name: poff.inscaping.eu/

on:
    release:
        types: [ published ]
        branches: [ staging_poff ]
    workflow_dispatch:

jobs:
    deploy:
        name: SCP files to server
        runs-on: ubuntu-latest
        steps:
        -   name: ls -a via ssh
            uses: fifsky/ssh-action@master
            with:
                command: |
                    rsync -avzr --delete domeenid/www.inscaping.eu/web/poff_staging/* domeenid/www.inscaping.eu/web/poff_live/
                host: inscaping.eu
                user: virt84398
                key: ${{ secrets.DEPLOY_KEY }}
